backend:
  name: github
  repo: UnknoWnCoder998/IXmed
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    fields:
      - {label: "Название", name: "title", widget: "string"}

      - {label: "Описание", name: "body", widget: "text"}
